### ISSUE TITLE
Ne spašava se odgovorni nastavnik i administrator ima mogućnost unosa odgovornog nastavnika.

### ISSUE THREAD

**Issue by sanilmusic** [SoftverInzenjeringETFSA/SI2016_TIM9#15]
**Komponente**

- Classrooms kontroler u EmberJS-u (/classrooms)
- ClassroomController u backend-u

**Revizija**
ebfcbf30e7ce0a9de42e2b4e368da264aa37f6b6

**Opis**
Prilikom inicijalnog unosa sale, administratoru se nudi mogućnost da unese odgovornog nastavnika. Administrator ne treba imati pravo unošenja odgovornog nastavnika. Ipak, u slučaju da se odgovorni nastavnik izabere tokom unošenja sale, isti neće biti spašen u sistem.

**Koraci za reproduciranje**

1. Otvoriti interfejs za kreiranje nove sale
2. Unijeti potrebne podatke, odabrati tip “Laboratorija” i izabrati odgovornog nastavnika (što ne bi trebalo biti dozvoljeno)
3. Sačuvati novu salu klikom na dugme "Dodaj"
4. Lista sala će se automatski osvježiti. Prikazat će se i nova sala, pri čemu polje odgovornog nastavnika neće biti popunjeno.

**Dodatni resursi**
![image17](https://cloud.githubusercontent.com/assets/4403018/26762481/58fdd5d6-4943-11e7-8c27-1f2733cb99fc.png)

![image6](https://cloud.githubusercontent.com/assets/4403018/26762495/7521f472-4943-11e7-9cde-785b20e91c49.png)

![image28](https://cloud.githubusercontent.com/assets/4403018/26762499/812111cc-4943-11e7-8e9a-61a98825f02d.png)

**Pojašnjenje**
Ovo pojašnjenje se odnosi na primjer sa slika. Odgovornog nastavnika unosi operater, tako da polje ne bi trebalo biti prikazano. U slučaju da polje ipak postoji, tada bi u koloni “Odgovorna osoba” trebalo pisati “Emir Cogo”, tj. ime nastavnika koji je odabran kao odgovorni nastavnik za laboratoriju. Kako se vidi na slikama, zapis o odgovornom nastavniku nije sačuvan u bazu podataka.

**Comment by liliumdev** [comment]
Ukinuto pravo administratoru da unosi odgovornog nastavnika. 

TO-DO: Potrebno dodati mogućnost operatoru da unosi odgovornog nastavnika.
